# Generated by Django 6.0.3 on 2026-04-06 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Monthly rent in €')),
                ('size', models.PositiveIntegerField(help_text='Room size in m²')),
                ('room_type', models.CharField(choices=[('private', 'Private room'), ('shared', 'Shared room'), ('studio', 'Studio')], default='private', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('rented', 'Rented')], default='active', max_length=20)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('students_allowed', models.BooleanField(default=True)),
                ('preferred_schedule', models.CharField(choices=[('early', 'Early bird'), ('night', 'Night owl'), ('normal', 'Standard')], default='normal', max_length=20)),
                ('preferred_noise', models.CharField(choices=[('quiet', 'Quiet'), ('medium', 'Moderate'), ('loud', 'Lively')], default='medium', max_length=20)),
                ('available_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
